name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'prophecy-bigquery'

model-paths: [ "models" ]
seed-paths: [ "seeds" ]
test-paths: [ "tests" ]
analysis-paths: [ "analysis" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [ ">=1.0.0", "<2.0.0" ]

models:
  jaffle_shop:
    materialized: table
    staging:
      materialized: view

vars:
  # The `start_date` variable will be accessible in all resources
  start_date: '2016-06-01'
  # The `platforms` variable is only accessible to resources in the my_dbt_project project
  my_dbt_project:
    platforms: [ 'web', 'mobile' ]
  myString: 'Random big string'
  my_int: -1234
  mySimpleInt: 1234