# ==================
# Project Details
# ==================
name: "jaffle_shop"
config-version: 2
require-dbt-version:
- ">=1.0.0"
- "<2.0.0"
version: "0.1"
profile: "prophecy-bigquery"

# ==================
# File Path Configs
# ==================
test-paths:
- "tests"
clean-targets:
- "target"
- "dbt_modules"
- "logs"
snapshot-paths:
- "snapshots"
seed-paths:
- "seeds"
model-paths:
- "models"
- "prophecy-sources"
analysis-paths:
- "analysis"
macro-paths:
- "macros"
target-path: "target"

# ==================
# Variable Configs
# ==================
vars:
  mySimpleInt: 1234
  myString: "Random big string"
  my_dbt_project:
    platforms:
    - "web"
    - "mobile"
  my_int: -1234
  start_date: "2016-06-01"

# ==================
# Model Configs
# ==================
models:
  jaffle_shop:
    materialized: "table"
    staging:
      materialized: "view"
