---
version: 2
snapshots:
- name: "orders_snapshot"
  columns:
  - name: "dbt_valid_to"
    dataType:
      type: "Date"
  - name: "order_id"
    dataType:
      type: "Integer"
  - name: "dbt_updated_at"
    dataType:
      type: "Date"
  - name: "dbt_valid_from"
    dataType:
      type: "Date"
  - name: "order_date"
    dataType:
      type: "Date"
  - name: "status"
    dataType:
      type: "String"
  - name: "dbt_scd_id"
    dataType:
      type: "String"
  tests: []
- name: "customer_with_subgraph_snapshot"
  columns:
  - name: "first_name"
    dataType:
      type: "String"
  - name: "customer_id"
    dataType:
      type: "Integer"
  - name: "customer_lifetime_value"
    dataType:
      type: "Double"
  - name: "first_order"
    dataType:
      type: "Date"
  - name: "last_name"
    dataType:
      type: "String"
  - name: "most_recent_order"
    dataType:
      type: "Date"
  - name: "total_orders"
    dataType:
      type: "Bigint"
  tests: []
